/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.heathensoft.test;

public class Adder {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static int add(int a, int b) {
        return a + b;
    }
}
